package net.mcreator.boh.compat.mc.world.level.block;

import net.mcreator.boh.compat.registry.LegacyIds;

/** 1.20 Blocks constants resolved through LegacyIds (Et Futurum targets when installed). Generated by tools/genconsts.sh. */
public final class Blocks {

    public static final net.minecraft.block.Block AIR = LegacyIds.blockOf("air");
    public static final net.minecraft.block.Block FIRE = LegacyIds.blockOf("fire");
    public static final net.minecraft.block.Block SPRUCE_LOG = LegacyIds.blockOf("spruce_log");
    public static final net.minecraft.block.Block OAK_LOG = LegacyIds.blockOf("oak_log");
    public static final net.minecraft.block.Block MANGROVE_LOG = LegacyIds.blockOf("mangrove_log");
    public static final net.minecraft.block.Block JUNGLE_LOG = LegacyIds.blockOf("jungle_log");
    public static final net.minecraft.block.Block DARK_OAK_LOG = LegacyIds.blockOf("dark_oak_log");
    public static final net.minecraft.block.Block CHERRY_LOG = LegacyIds.blockOf("cherry_log");
    public static final net.minecraft.block.Block BIRCH_LOG = LegacyIds.blockOf("birch_log");
    public static final net.minecraft.block.Block ACACIA_LOG = LegacyIds.blockOf("acacia_log");
    public static final net.minecraft.block.Block WHEAT = LegacyIds.blockOf("wheat");
    public static final net.minecraft.block.Block GRASS_BLOCK = LegacyIds.blockOf("grass_block");
    public static final net.minecraft.block.Block WHITE_WOOL = LegacyIds.blockOf("white_wool");
    public static final net.minecraft.block.Block DIRT = LegacyIds.blockOf("dirt");
    public static final net.minecraft.block.Block WATER = LegacyIds.blockOf("water");
    public static final net.minecraft.block.Block VOID_AIR = LegacyIds.blockOf("void_air");
    public static final net.minecraft.block.Block CAVE_AIR = LegacyIds.blockOf("cave_air");
    public static final net.minecraft.block.Block ROSE_BUSH = LegacyIds.blockOf("rose_bush");
    public static final net.minecraft.block.Block PUMPKIN_STEM = LegacyIds.blockOf("pumpkin_stem");
    public static final net.minecraft.block.Block POTATOES = LegacyIds.blockOf("potatoes");
    public static final net.minecraft.block.Block PODZOL = LegacyIds.blockOf("podzol");
    public static final net.minecraft.block.Block OBSIDIAN = LegacyIds.blockOf("obsidian");
    public static final net.minecraft.block.Block MELON_STEM = LegacyIds.blockOf("melon_stem");
    public static final net.minecraft.block.Block FARMLAND = LegacyIds.blockOf("farmland");
    public static final net.minecraft.block.Block COARSE_DIRT = LegacyIds.blockOf("coarse_dirt");
    public static final net.minecraft.block.Block CARROTS = LegacyIds.blockOf("carrots");
    public static final net.minecraft.block.Block BEETROOTS = LegacyIds.blockOf("beetroots");
    public static final net.minecraft.block.Block ATTACHED_PUMPKIN_STEM = LegacyIds.blockOf("attached_pumpkin_stem");
    public static final net.minecraft.block.Block ATTACHED_MELON_STEM = LegacyIds.blockOf("attached_melon_stem");
    public static final net.minecraft.block.Block STONE = LegacyIds.blockOf("stone");
    public static final net.minecraft.block.Block COBBLESTONE = LegacyIds.blockOf("cobblestone");
    public static final net.minecraft.block.Block GLASS = LegacyIds.blockOf("glass");
    public static final net.minecraft.block.Block TORCH = LegacyIds.blockOf("torch");
    public static final net.minecraft.block.Block LAVA = LegacyIds.blockOf("lava");
    public static final net.minecraft.block.Block SAND = LegacyIds.blockOf("sand");
    public static final net.minecraft.block.Block GRAVEL = LegacyIds.blockOf("gravel");
    public static final net.minecraft.block.Block BEDROCK = LegacyIds.blockOf("bedrock");
    public static final net.minecraft.block.Block OAK_PLANKS = LegacyIds.blockOf("oak_planks");
    public static final net.minecraft.block.Block OAK_LEAVES = LegacyIds.blockOf("oak_leaves");
    public static final net.minecraft.block.Block GRASS = LegacyIds.blockOf("grass");
    public static final net.minecraft.block.Block TALL_GRASS = LegacyIds.blockOf("tall_grass");

    private Blocks() {}
}
