package net.mcreator.boh.init;

import net.mcreator.boh.block.AnalogTVBillBlock;
import net.mcreator.boh.block.AnalogTVBillyBlock;
import net.mcreator.boh.block.AnalogTVBoiledBlock;
import net.mcreator.boh.block.AnalogTVCourageBlock;
import net.mcreator.boh.block.AnalogTVCoveBlock;
import net.mcreator.boh.block.AnalogTVFleshpitBlock;
import net.mcreator.boh.block.AnalogTVGeminiBlock;
import net.mcreator.boh.block.AnalogTVLocal58Block;
import net.mcreator.boh.block.AnalogTVMaxBlock;
import net.mcreator.boh.block.AnalogTVNeedleBlock;
import net.mcreator.boh.block.AnalogTVNoMoreBlock;
import net.mcreator.boh.block.AnalogTVOperatorBlock;
import net.mcreator.boh.block.AnalogTVSadakoBlock;
import net.mcreator.boh.block.AnalogTVShamrockBlock;
import net.mcreator.boh.block.AnalogTVSixBlock;
import net.mcreator.boh.block.AnalogTVStaticBlock;
import net.mcreator.boh.block.AnalogTVWyomingBlock;
import net.mcreator.boh.block.AnalogTelevisionBlock;
import net.mcreator.boh.block.AnalogtvsadakocBlock;
import net.mcreator.boh.block.BackroomsCeilingFillerBlock;
import net.mcreator.boh.block.BackroomsCeilingTileBlock;
import net.mcreator.boh.block.BackroomsFloorBlock;
import net.mcreator.boh.block.BackroomsLampBlock;
import net.mcreator.boh.block.BackroomsSocketBlock;
import net.mcreator.boh.block.BackroomsWallsBlock;
import net.mcreator.boh.block.BackroomsWallsBottomBlock;
import net.mcreator.boh.block.BackroomsWallsTopBlock;
import net.mcreator.boh.block.BlackWallnutSapplingBlock;
import net.mcreator.boh.block.BlackWalnutButtonBlock;
import net.mcreator.boh.block.BlackWalnutDoorBlock;
import net.mcreator.boh.block.BlackWalnutFenceBlock;
import net.mcreator.boh.block.BlackWalnutFenceGateBlock;
import net.mcreator.boh.block.BlackWalnutLeavesBlock;
import net.mcreator.boh.block.BlackWalnutLogBlock;
import net.mcreator.boh.block.BlackWalnutPlanksBlock;
import net.mcreator.boh.block.BlackWalnutPressurePlateBlock;
import net.mcreator.boh.block.BlackWalnutSlabBlock;
import net.mcreator.boh.block.BlackWalnutStairsBlock;
import net.mcreator.boh.block.BlackWalnutStrippedLogBlock;
import net.mcreator.boh.block.BlackWalnutStrippedWoodBlock;
import net.mcreator.boh.block.BlackWalnutTrapdoorBlock;
import net.mcreator.boh.block.BlackWalnutWoodBlock;
import net.mcreator.boh.block.BloodstoneBlockBlock;
import net.mcreator.boh.block.ComputerBlock;
import net.mcreator.boh.block.DogwoodButtonBlock;
import net.mcreator.boh.block.DogwoodDoorBlock;
import net.mcreator.boh.block.DogwoodFenceBlock;
import net.mcreator.boh.block.DogwoodFenceGateBlock;
import net.mcreator.boh.block.DogwoodLeavesBlock;
import net.mcreator.boh.block.DogwoodLogBlock;
import net.mcreator.boh.block.DogwoodPlanksBlock;
import net.mcreator.boh.block.DogwoodPressurePlateBlock;
import net.mcreator.boh.block.DogwoodSaplingBlock;
import net.mcreator.boh.block.DogwoodSlabBlock;
import net.mcreator.boh.block.DogwoodStairsBlock;
import net.mcreator.boh.block.DogwoodStrippedLogBlock;
import net.mcreator.boh.block.DogwoodStrippedWoodBlock;
import net.mcreator.boh.block.DogwoodTrapdoorBlock;
import net.mcreator.boh.block.DogwoodWoodBlock;
import net.mcreator.boh.block.DrawingSlenderBlock;
import net.mcreator.boh.block.DreamCatcherBlock;
import net.mcreator.boh.block.EscapeNightmareBlockBlock;
import net.mcreator.boh.block.GametableBlock;
import net.mcreator.boh.block.GasterBlockExitBlock;
import net.mcreator.boh.block.GasterBlockFloorBlock;
import net.mcreator.boh.block.GasterBlockWallBlock;
import net.mcreator.boh.block.GasterDoorBlock;
import net.mcreator.boh.block.GlowblockFigureBlock;
import net.mcreator.boh.block.GojibreathBlock;
import net.mcreator.boh.block.HolyFireBlock;
import net.mcreator.boh.block.JarOWispBlock;
import net.mcreator.boh.block.KindnessFlowerBlock;
import net.mcreator.boh.block.LifeformGrowthBlock;
import net.mcreator.boh.block.OvamorphBlock;
import net.mcreator.boh.block.OvamorphOpenBlock;
import net.mcreator.boh.block.PipeBlockBlock;
import net.mcreator.boh.block.PipeBurstBlock;
import net.mcreator.boh.block.PokerNightBlock;
import net.mcreator.boh.block.PumpkinPlayerLightsoruceBlock;
import net.mcreator.boh.block.RiftStabilizerBlock;
import net.mcreator.boh.block.SassafrasButtonBlock;
import net.mcreator.boh.block.SassafrasDoorBlock;
import net.mcreator.boh.block.SassafrasFenceBlock;
import net.mcreator.boh.block.SassafrasFenceGateBlock;
import net.mcreator.boh.block.SassafrasLeavesBlock;
import net.mcreator.boh.block.SassafrasLogBlock;
import net.mcreator.boh.block.SassafrasPlanksBlock;
import net.mcreator.boh.block.SassafrasPressurePlateBlock;
import net.mcreator.boh.block.SassafrasSaplingBlock;
import net.mcreator.boh.block.SassafrasSlabBlock;
import net.mcreator.boh.block.SassafrasStairsBlock;
import net.mcreator.boh.block.SassafrasStrippedLogBlock;
import net.mcreator.boh.block.SassafrasStrippedWoodBlock;
import net.mcreator.boh.block.SassafrasTrapdoorBlock;
import net.mcreator.boh.block.SassafrasWoodBlock;
import net.mcreator.boh.block.SinistreeButtonBlock;
import net.mcreator.boh.block.SinistreeDoorBlock;
import net.mcreator.boh.block.SinistreeFenceBlock;
import net.mcreator.boh.block.SinistreeFenceGateBlock;
import net.mcreator.boh.block.SinistreeLeavesBlock;
import net.mcreator.boh.block.SinistreeLogBlock;
import net.mcreator.boh.block.SinistreePlanksBlock;
import net.mcreator.boh.block.SinistreePressurePlateBlock;
import net.mcreator.boh.block.SinistreeSaplingBlock;
import net.mcreator.boh.block.SinistreeSlabBlock;
import net.mcreator.boh.block.SinistreeStairsBlock;
import net.mcreator.boh.block.SinistreeStrippedLogBlock;
import net.mcreator.boh.block.SinistreeStrippedWoodBlock;
import net.mcreator.boh.block.SinistreeTrapDoorBlock;
import net.mcreator.boh.block.SinistreeWoodBlock;
import net.mcreator.boh.block.SpinelBlockBlock;
import net.mcreator.boh.block.SpinelOreOreBlock;
import net.mcreator.boh.block.StudBaseplateBlock;
import net.mcreator.boh.block.StudPartBlock;
import net.mcreator.boh.block.TubbyCustardBlock;
import net.mcreator.boh.block.TwigTrapBlock;
import net.mcreator.boh.block.VitaCrawlBlock;
import net.mcreator.boh.block.VoodooDollBlock;
import net.mcreator.boh.block.XenomorphBloodBlock;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class BohModBlocks {
   public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, "boh");
   public static final RegistryObject<Block> XENOMORPH_BLOOD = REGISTRY.register("xenomorph_blood", () -> new XenomorphBloodBlock());
   public static final RegistryObject<Block> OVAMORPH = REGISTRY.register("ovamorph", () -> new OvamorphBlock());
   public static final RegistryObject<Block> OVAMORPH_OPEN = REGISTRY.register("ovamorph_open", () -> new OvamorphOpenBlock());
   public static final RegistryObject<Block> DRAWING_SLENDER = REGISTRY.register("drawing_slender", () -> new DrawingSlenderBlock());
   public static final RegistryObject<Block> KINDNESS_FLOWER = REGISTRY.register("kindness_flower", () -> new KindnessFlowerBlock());
   public static final RegistryObject<Block> LIFEFORM_GROWTH = REGISTRY.register("lifeform_growth", () -> new LifeformGrowthBlock());
   public static final RegistryObject<Block> VOODOO_DOLL = REGISTRY.register("voodoo_doll", () -> new VoodooDollBlock());
   public static final RegistryObject<Block> ANALOG_TV_STATIC = REGISTRY.register("analog_tv_static", () -> new AnalogTVStaticBlock());
   public static final RegistryObject<Block> ANALOG_TV_SIX = REGISTRY.register("analog_tv_six", () -> new AnalogTVSixBlock());
   public static final RegistryObject<Block> SPINEL_ORE_ORE = REGISTRY.register("spinel_ore_ore", () -> new SpinelOreOreBlock());
   public static final RegistryObject<Block> GOJIBREATH = REGISTRY.register("gojibreath", () -> new GojibreathBlock());
   public static final RegistryObject<Block> ANALOG_TV_SADAKO = REGISTRY.register("analog_tv_sadako", () -> new AnalogTVSadakoBlock());
   public static final RegistryObject<Block> ANALOGTVSADAKOC = REGISTRY.register("analogtvsadakoc", () -> new AnalogtvsadakocBlock());
   public static final RegistryObject<Block> ANALOG_TELEVISION = REGISTRY.register("analog_television", () -> new AnalogTelevisionBlock());
   public static final RegistryObject<Block> BACKROOMS_FLOOR = REGISTRY.register("backrooms_floor", () -> new BackroomsFloorBlock());
   public static final RegistryObject<Block> BACKROOMS_WALLS = REGISTRY.register("backrooms_walls", () -> new BackroomsWallsBlock());
   public static final RegistryObject<Block> BACKROOMS_CEILING_TILE = REGISTRY.register("backrooms_ceiling_tile", () -> new BackroomsCeilingTileBlock());
   public static final RegistryObject<Block> BACKROOMS_LAMP = REGISTRY.register("backrooms_lamp", () -> new BackroomsLampBlock());
   public static final RegistryObject<Block> GASTER_DOOR = REGISTRY.register("gaster_door", () -> new GasterDoorBlock());
   public static final RegistryObject<Block> GASTER_BLOCK_WALL = REGISTRY.register("gaster_block_wall", () -> new GasterBlockWallBlock());
   public static final RegistryObject<Block> GASTER_BLOCK_FLOOR = REGISTRY.register("gaster_block_floor", () -> new GasterBlockFloorBlock());
   public static final RegistryObject<Block> GASTER_BLOCK_EXIT = REGISTRY.register("gaster_block_exit", () -> new GasterBlockExitBlock());
   public static final RegistryObject<Block> GAMETABLE = REGISTRY.register("gametable", () -> new GametableBlock());
   public static final RegistryObject<Block> BACKROOMS_CEILING_FILLER = REGISTRY.register("backrooms_ceiling_filler", () -> new BackroomsCeilingFillerBlock());
   public static final RegistryObject<Block> ANALOG_TV_BILL = REGISTRY.register("analog_tv_bill", () -> new AnalogTVBillBlock());
   public static final RegistryObject<Block> ANALOG_TV_BILLY = REGISTRY.register("analog_tv_billy", () -> new AnalogTVBillyBlock());
   public static final RegistryObject<Block> ANALOG_TV_COURAGE = REGISTRY.register("analog_tv_courage", () -> new AnalogTVCourageBlock());
   public static final RegistryObject<Block> ANALOG_TV_COVE = REGISTRY.register("analog_tv_cove", () -> new AnalogTVCoveBlock());
   public static final RegistryObject<Block> ANALOG_TV_FLESHPIT = REGISTRY.register("analog_tv_fleshpit", () -> new AnalogTVFleshpitBlock());
   public static final RegistryObject<Block> ANALOG_TV_GEMINI = REGISTRY.register("analog_tv_gemini", () -> new AnalogTVGeminiBlock());
   public static final RegistryObject<Block> ANALOG_TV_LOCAL_58 = REGISTRY.register("analog_tv_local_58", () -> new AnalogTVLocal58Block());
   public static final RegistryObject<Block> ANALOG_TV_MAX = REGISTRY.register("analog_tv_max", () -> new AnalogTVMaxBlock());
   public static final RegistryObject<Block> ANALOG_TV_NEEDLE = REGISTRY.register("analog_tv_needle", () -> new AnalogTVNeedleBlock());
   public static final RegistryObject<Block> ANALOG_TV_NO_MORE = REGISTRY.register("analog_tv_no_more", () -> new AnalogTVNoMoreBlock());
   public static final RegistryObject<Block> ANALOG_TV_OPERATOR = REGISTRY.register("analog_tv_operator", () -> new AnalogTVOperatorBlock());
   public static final RegistryObject<Block> ANALOG_TV_SHAMROCK = REGISTRY.register("analog_tv_shamrock", () -> new AnalogTVShamrockBlock());
   public static final RegistryObject<Block> ANALOG_TV_WYOMING = REGISTRY.register("analog_tv_wyoming", () -> new AnalogTVWyomingBlock());
   public static final RegistryObject<Block> TWIG_TRAP = REGISTRY.register("twig_trap", () -> new TwigTrapBlock());
   public static final RegistryObject<Block> BACKROOMS_WALLS_TOP = REGISTRY.register("backrooms_walls_top", () -> new BackroomsWallsTopBlock());
   public static final RegistryObject<Block> BACKROOMS_WALLS_BOTTOM = REGISTRY.register("backrooms_walls_bottom", () -> new BackroomsWallsBottomBlock());
   public static final RegistryObject<Block> BACKROOMS_SOCKET = REGISTRY.register("backrooms_socket", () -> new BackroomsSocketBlock());
   public static final RegistryObject<Block> PIPE_BLOCK = REGISTRY.register("pipe_block", () -> new PipeBlockBlock());
   public static final RegistryObject<Block> PIPE_BURST = REGISTRY.register("pipe_burst", () -> new PipeBurstBlock());
   public static final RegistryObject<Block> ESCAPE_NIGHTMARE_BLOCK = REGISTRY.register("escape_nightmare_block", () -> new EscapeNightmareBlockBlock());
   public static final RegistryObject<Block> ANALOG_TV_BOILED = REGISTRY.register("analog_tv_boiled", () -> new AnalogTVBoiledBlock());
   public static final RegistryObject<Block> RIFT_STABILIZER = REGISTRY.register("rift_stabilizer", () -> new RiftStabilizerBlock());
   public static final RegistryObject<Block> COMPUTER = REGISTRY.register("computer", () -> new ComputerBlock());
   public static final RegistryObject<Block> DREAM_CATCHER = REGISTRY.register("dream_catcher", () -> new DreamCatcherBlock());
   public static final RegistryObject<Block> TUBBY_CUSTARD = REGISTRY.register("tubby_custard", () -> new TubbyCustardBlock());
   public static final RegistryObject<Block> SPINEL_BLOCK = REGISTRY.register("spinel_block", () -> new SpinelBlockBlock());
   public static final RegistryObject<Block> BLOODSTONE_BLOCK = REGISTRY.register("bloodstone_block", () -> new BloodstoneBlockBlock());
   public static final RegistryObject<Block> HOLY_FIRE = REGISTRY.register("holy_fire", () -> new HolyFireBlock());
   public static final RegistryObject<Block> GLOWBLOCK_FIGURE = REGISTRY.register("glowblock_figure", () -> new GlowblockFigureBlock());
   public static final RegistryObject<Block> BLACK_WALNUT_WOOD = REGISTRY.register("black_walnut_wood", () -> new BlackWalnutWoodBlock());
   public static final RegistryObject<Block> BLACK_WALNUT_LOG = REGISTRY.register("black_walnut_log", () -> new BlackWalnutLogBlock());
   public static final RegistryObject<Block> BLACK_WALNUT_PLANKS = REGISTRY.register("black_walnut_planks", () -> new BlackWalnutPlanksBlock());
   public static final RegistryObject<Block> BLACK_WALNUT_LEAVES = REGISTRY.register("black_walnut_leaves", () -> new BlackWalnutLeavesBlock());
   public static final RegistryObject<Block> BLACK_WALNUT_STAIRS = REGISTRY.register("black_walnut_stairs", () -> new BlackWalnutStairsBlock());
   public static final RegistryObject<Block> BLACK_WALNUT_SLAB = REGISTRY.register("black_walnut_slab", () -> new BlackWalnutSlabBlock());
   public static final RegistryObject<Block> BLACK_WALNUT_FENCE = REGISTRY.register("black_walnut_fence", () -> new BlackWalnutFenceBlock());
   public static final RegistryObject<Block> BLACK_WALNUT_FENCE_GATE = REGISTRY.register("black_walnut_fence_gate", () -> new BlackWalnutFenceGateBlock());
   public static final RegistryObject<Block> BLACK_WALNUT_PRESSURE_PLATE = REGISTRY.register(
      "black_walnut_pressure_plate", () -> new BlackWalnutPressurePlateBlock()
   );
   public static final RegistryObject<Block> BLACK_WALNUT_BUTTON = REGISTRY.register("black_walnut_button", () -> new BlackWalnutButtonBlock());
   public static final RegistryObject<Block> DOGWOOD_WOOD = REGISTRY.register("dogwood_wood", () -> new DogwoodWoodBlock());
   public static final RegistryObject<Block> DOGWOOD_LOG = REGISTRY.register("dogwood_log", () -> new DogwoodLogBlock());
   public static final RegistryObject<Block> DOGWOOD_PLANKS = REGISTRY.register("dogwood_planks", () -> new DogwoodPlanksBlock());
   public static final RegistryObject<Block> DOGWOOD_LEAVES = REGISTRY.register("dogwood_leaves", () -> new DogwoodLeavesBlock());
   public static final RegistryObject<Block> DOGWOOD_STAIRS = REGISTRY.register("dogwood_stairs", () -> new DogwoodStairsBlock());
   public static final RegistryObject<Block> DOGWOOD_SLAB = REGISTRY.register("dogwood_slab", () -> new DogwoodSlabBlock());
   public static final RegistryObject<Block> DOGWOOD_FENCE = REGISTRY.register("dogwood_fence", () -> new DogwoodFenceBlock());
   public static final RegistryObject<Block> DOGWOOD_FENCE_GATE = REGISTRY.register("dogwood_fence_gate", () -> new DogwoodFenceGateBlock());
   public static final RegistryObject<Block> DOGWOOD_PRESSURE_PLATE = REGISTRY.register("dogwood_pressure_plate", () -> new DogwoodPressurePlateBlock());
   public static final RegistryObject<Block> DOGWOOD_BUTTON = REGISTRY.register("dogwood_button", () -> new DogwoodButtonBlock());
   public static final RegistryObject<Block> SASSAFRAS_WOOD = REGISTRY.register("sassafras_wood", () -> new SassafrasWoodBlock());
   public static final RegistryObject<Block> SASSAFRAS_LOG = REGISTRY.register("sassafras_log", () -> new SassafrasLogBlock());
   public static final RegistryObject<Block> SASSAFRAS_PLANKS = REGISTRY.register("sassafras_planks", () -> new SassafrasPlanksBlock());
   public static final RegistryObject<Block> SASSAFRAS_LEAVES = REGISTRY.register("sassafras_leaves", () -> new SassafrasLeavesBlock());
   public static final RegistryObject<Block> SASSAFRAS_STAIRS = REGISTRY.register("sassafras_stairs", () -> new SassafrasStairsBlock());
   public static final RegistryObject<Block> SASSAFRAS_SLAB = REGISTRY.register("sassafras_slab", () -> new SassafrasSlabBlock());
   public static final RegistryObject<Block> SASSAFRAS_FENCE = REGISTRY.register("sassafras_fence", () -> new SassafrasFenceBlock());
   public static final RegistryObject<Block> SASSAFRAS_FENCE_GATE = REGISTRY.register("sassafras_fence_gate", () -> new SassafrasFenceGateBlock());
   public static final RegistryObject<Block> SASSAFRAS_PRESSURE_PLATE = REGISTRY.register("sassafras_pressure_plate", () -> new SassafrasPressurePlateBlock());
   public static final RegistryObject<Block> SASSAFRAS_BUTTON = REGISTRY.register("sassafras_button", () -> new SassafrasButtonBlock());
   public static final RegistryObject<Block> JAR_O_WISP = REGISTRY.register("jar_o_wisp", () -> new JarOWispBlock());
   public static final RegistryObject<Block> BLACK_WALNUT_STRIPPED_WOOD = REGISTRY.register(
      "black_walnut_stripped_wood", () -> new BlackWalnutStrippedWoodBlock()
   );
   public static final RegistryObject<Block> BLACK_WALNUT_STRIPPED_LOG = REGISTRY.register("black_walnut_stripped_log", () -> new BlackWalnutStrippedLogBlock());
   public static final RegistryObject<Block> BLACK_WALNUT_DOOR = REGISTRY.register("black_walnut_door", () -> new BlackWalnutDoorBlock());
   public static final RegistryObject<Block> BLACK_WALNUT_TRAPDOOR = REGISTRY.register("black_walnut_trapdoor", () -> new BlackWalnutTrapdoorBlock());
   public static final RegistryObject<Block> DOGWOOD_STRIPPED_WOOD = REGISTRY.register("dogwood_stripped_wood", () -> new DogwoodStrippedWoodBlock());
   public static final RegistryObject<Block> DOGWOOD_STRIPPED_LOG = REGISTRY.register("dogwood_stripped_log", () -> new DogwoodStrippedLogBlock());
   public static final RegistryObject<Block> DOGWOOD_DOOR = REGISTRY.register("dogwood_door", () -> new DogwoodDoorBlock());
   public static final RegistryObject<Block> DOGWOOD_TRAPDOOR = REGISTRY.register("dogwood_trapdoor", () -> new DogwoodTrapdoorBlock());
   public static final RegistryObject<Block> SASSAFRAS_STRIPPED_WOOD = REGISTRY.register("sassafras_stripped_wood", () -> new SassafrasStrippedWoodBlock());
   public static final RegistryObject<Block> SASSAFRAS_STRIPPED_LOG = REGISTRY.register("sassafras_stripped_log", () -> new SassafrasStrippedLogBlock());
   public static final RegistryObject<Block> SASSAFRAS_DOOR = REGISTRY.register("sassafras_door", () -> new SassafrasDoorBlock());
   public static final RegistryObject<Block> SASSAFRAS_TRAPDOOR = REGISTRY.register("sassafras_trapdoor", () -> new SassafrasTrapdoorBlock());
   public static final RegistryObject<Block> BLACK_WALLNUT_SAPPLING = REGISTRY.register("black_wallnut_sappling", () -> new BlackWallnutSapplingBlock());
   public static final RegistryObject<Block> DOGWOOD_SAPLING = REGISTRY.register("dogwood_sapling", () -> new DogwoodSaplingBlock());
   public static final RegistryObject<Block> SASSAFRAS_SAPLING = REGISTRY.register("sassafras_sapling", () -> new SassafrasSaplingBlock());
   public static final RegistryObject<Block> VITA_CRAWL = REGISTRY.register("vita_crawl", () -> new VitaCrawlBlock());
   public static final RegistryObject<Block> POKER_NIGHT = REGISTRY.register("poker_night", () -> new PokerNightBlock());
   public static final RegistryObject<Block> PUMPKIN_PLAYER_LIGHTSORUCE = REGISTRY.register(
      "pumpkin_player_lightsoruce", () -> new PumpkinPlayerLightsoruceBlock()
   );
   public static final RegistryObject<Block> SINISTREE_WOOD = REGISTRY.register("sinistree_wood", () -> new SinistreeWoodBlock());
   public static final RegistryObject<Block> SINISTREE_LOG = REGISTRY.register("sinistree_log", () -> new SinistreeLogBlock());
   public static final RegistryObject<Block> SINISTREE_PLANKS = REGISTRY.register("sinistree_planks", () -> new SinistreePlanksBlock());
   public static final RegistryObject<Block> SINISTREE_LEAVES = REGISTRY.register("sinistree_leaves", () -> new SinistreeLeavesBlock());
   public static final RegistryObject<Block> SINISTREE_STAIRS = REGISTRY.register("sinistree_stairs", () -> new SinistreeStairsBlock());
   public static final RegistryObject<Block> SINISTREE_SLAB = REGISTRY.register("sinistree_slab", () -> new SinistreeSlabBlock());
   public static final RegistryObject<Block> SINISTREE_FENCE = REGISTRY.register("sinistree_fence", () -> new SinistreeFenceBlock());
   public static final RegistryObject<Block> SINISTREE_FENCE_GATE = REGISTRY.register("sinistree_fence_gate", () -> new SinistreeFenceGateBlock());
   public static final RegistryObject<Block> SINISTREE_PRESSURE_PLATE = REGISTRY.register("sinistree_pressure_plate", () -> new SinistreePressurePlateBlock());
   public static final RegistryObject<Block> SINISTREE_BUTTON = REGISTRY.register("sinistree_button", () -> new SinistreeButtonBlock());
   public static final RegistryObject<Block> SINISTREE_STRIPPED_WOOD = REGISTRY.register("sinistree_stripped_wood", () -> new SinistreeStrippedWoodBlock());
   public static final RegistryObject<Block> SINISTREE_STRIPPED_LOG = REGISTRY.register("sinistree_stripped_log", () -> new SinistreeStrippedLogBlock());
   public static final RegistryObject<Block> SINISTREE_DOOR = REGISTRY.register("sinistree_door", () -> new SinistreeDoorBlock());
   public static final RegistryObject<Block> SINISTREE_TRAP_DOOR = REGISTRY.register("sinistree_trap_door", () -> new SinistreeTrapDoorBlock());
   public static final RegistryObject<Block> SINISTREE_SAPLING = REGISTRY.register("sinistree_sapling", () -> new SinistreeSaplingBlock());
   public static final RegistryObject<Block> STUD_BASEPLATE = REGISTRY.register("stud_baseplate", () -> new StudBaseplateBlock());
   public static final RegistryObject<Block> STUD_PART = REGISTRY.register("stud_part", () -> new StudPartBlock());
}
