package net.mcreator.boh.init;

import cpw.mods.fml.common.eventhandler.SubscribeEvent;
import net.mcreator.boh.client.renderer.AnglerRenderer;
import net.mcreator.boh.client.renderer.AoOniRenderer;
import net.mcreator.boh.client.renderer.BaldiRenderer;
import net.mcreator.boh.client.renderer.BenDrownedRenderer;
import net.mcreator.boh.client.renderer.BigDaddyRenderer;
import net.mcreator.boh.client.renderer.BloodSpillRenderer;
import net.mcreator.boh.client.renderer.BloodwaveRenderer;
import net.mcreator.boh.client.renderer.BoiledOneRenderer;
import net.mcreator.boh.client.renderer.BookSimonRenderer;
import net.mcreator.boh.client.renderer.BruceRenderer;
import net.mcreator.boh.client.renderer.CartoonCatRenderer;
import net.mcreator.boh.client.renderer.CelebiRenderer;
import net.mcreator.boh.client.renderer.ChestbursterRenderer;
import net.mcreator.boh.client.renderer.ChuckyGrabRenderer;
import net.mcreator.boh.client.renderer.ChuckyRenderer;
import net.mcreator.boh.client.renderer.DeathHorseRenderer;
import net.mcreator.boh.client.renderer.DecoyDogRenderer;
import net.mcreator.boh.client.renderer.DeerMimicRenderer;
import net.mcreator.boh.client.renderer.DeerRenderer;
import net.mcreator.boh.client.renderer.DemogorgonRenderer;
import net.mcreator.boh.client.renderer.DemonRenderer;
import net.mcreator.boh.client.renderer.EntityWellRenderer;
import net.mcreator.boh.client.renderer.ExeMonitorRenderer;
import net.mcreator.boh.client.renderer.EyelessJackRenderer;
import net.mcreator.boh.client.renderer.FacehuggerRenderer;
import net.mcreator.boh.client.renderer.FamineHorseRenderer;
import net.mcreator.boh.client.renderer.FigureRenderer;
import net.mcreator.boh.client.renderer.FlatwoodsMonsterRenderer;
import net.mcreator.boh.client.renderer.FlowersRenderer;
import net.mcreator.boh.client.renderer.FreddyKruegerRenderer;
import net.mcreator.boh.client.renderer.FresnoNightcrawlerRenderer;
import net.mcreator.boh.client.renderer.FuwattiRenderer;
import net.mcreator.boh.client.renderer.GasterRenderer;
import net.mcreator.boh.client.renderer.GhostRenderer;
import net.mcreator.boh.client.renderer.GhostfaceDecoyRenderer;
import net.mcreator.boh.client.renderer.GhostfaceRenderer;
import net.mcreator.boh.client.renderer.GojiRenderer;
import net.mcreator.boh.client.renderer.GoldHostileRenderer;
import net.mcreator.boh.client.renderer.GoldLostRenderer;
import net.mcreator.boh.client.renderer.GraftonMonsterRenderer;
import net.mcreator.boh.client.renderer.GrannyRenderer;
import net.mcreator.boh.client.renderer.GrayAlienRenderer;
import net.mcreator.boh.client.renderer.HerobrineRenderer;
import net.mcreator.boh.client.renderer.HypnoRenderer;
import net.mcreator.boh.client.renderer.InkDemonRenderer;
import net.mcreator.boh.client.renderer.JackalopeRenderer;
import net.mcreator.boh.client.renderer.JamesSunderlandRenderer;
import net.mcreator.boh.client.renderer.JaneTheKillerRenderer;
import net.mcreator.boh.client.renderer.JasonMaskRenderer;
import net.mcreator.boh.client.renderer.JasonVoorheesRenderer;
import net.mcreator.boh.client.renderer.JeffTheKillerRenderer;
import net.mcreator.boh.client.renderer.KirieHimuroRenderer;
import net.mcreator.boh.client.renderer.KrampusRenderer;
import net.mcreator.boh.client.renderer.KrasueRenderer;
import net.mcreator.boh.client.renderer.LaughingJackRenderer;
import net.mcreator.boh.client.renderer.LeatherfaceRenderer;
import net.mcreator.boh.client.renderer.LifeformRenderer;
import net.mcreator.boh.client.renderer.LightHeadRenderer;
import net.mcreator.boh.client.renderer.LittleSisterRenderer;
import net.mcreator.boh.client.renderer.MXRenderer;
import net.mcreator.boh.client.renderer.MartianDroneRenderer;
import net.mcreator.boh.client.renderer.MichaelDaviesRenderer;
import net.mcreator.boh.client.renderer.MichaelMyersRenderer;
import net.mcreator.boh.client.renderer.MothlingRenderer;
import net.mcreator.boh.client.renderer.MothmanRenderer;
import net.mcreator.boh.client.renderer.NPC000Renderer;
import net.mcreator.boh.client.renderer.NecoArcRenderer;
import net.mcreator.boh.client.renderer.NemesisRenderer;
import net.mcreator.boh.client.renderer.NewbornRenderer;
import net.mcreator.boh.client.renderer.NothingThereRenderer;
import net.mcreator.boh.client.renderer.PatrickBatemanRenderer;
import net.mcreator.boh.client.renderer.PestilenceHorseRenderer;
import net.mcreator.boh.client.renderer.PhantomBBRenderer;
import net.mcreator.boh.client.renderer.PhantomChicaRenderer;
import net.mcreator.boh.client.renderer.PhantomFoxyRenderer;
import net.mcreator.boh.client.renderer.PhantomFreddyRenderer;
import net.mcreator.boh.client.renderer.PhantomMangleRenderer;
import net.mcreator.boh.client.renderer.PhantomPuppetRenderer;
import net.mcreator.boh.client.renderer.PredatorRenderer;
import net.mcreator.boh.client.renderer.PredatorSightRenderer;
import net.mcreator.boh.client.renderer.PumpkinPlayerRenderer;
import net.mcreator.boh.client.renderer.PyramidHeadRenderer;
import net.mcreator.boh.client.renderer.REDRenderer;
import net.mcreator.boh.client.renderer.RaatmaRenderer;
import net.mcreator.boh.client.renderer.RabbidRenderer;
import net.mcreator.boh.client.renderer.RakeRenderer;
import net.mcreator.boh.client.renderer.RatRenderer;
import net.mcreator.boh.client.renderer.RatazanaRenderer;
import net.mcreator.boh.client.renderer.RendProjectileRenderer;
import net.mcreator.boh.client.renderer.RexyRenderer;
import net.mcreator.boh.client.renderer.RollingGiantRenderer;
import net.mcreator.boh.client.renderer.RussianSleepExperimentRenderer;
import net.mcreator.boh.client.renderer.SadakoRenderer;
import net.mcreator.boh.client.renderer.SaucerRenderer;
import net.mcreator.boh.client.renderer.SawRunnerRenderer;
import net.mcreator.boh.client.renderer.ScissormanRenderer;
import net.mcreator.boh.client.renderer.SeedEaterRenderer;
import net.mcreator.boh.client.renderer.ShotgunProjectileRenderer;
import net.mcreator.boh.client.renderer.SimonhenrikssonRenderer;
import net.mcreator.boh.client.renderer.SirenHeadRenderer;
import net.mcreator.boh.client.renderer.SixRenderer;
import net.mcreator.boh.client.renderer.SlenderManRenderer;
import net.mcreator.boh.client.renderer.SmileDogRenderer;
import net.mcreator.boh.client.renderer.SonicBoomRenderer;
import net.mcreator.boh.client.renderer.SonicExeRenderer;
import net.mcreator.boh.client.renderer.SotirisRenderer;
import net.mcreator.boh.client.renderer.SouichiRenderer;
import net.mcreator.boh.client.renderer.Specimen9BossRenderer;
import net.mcreator.boh.client.renderer.SpringtrapRenderer;
import net.mcreator.boh.client.renderer.SquidwardDoomedRenderer;
import net.mcreator.boh.client.renderer.SquidwardRenderer;
import net.mcreator.boh.client.renderer.StiltwalkerRenderer;
import net.mcreator.boh.client.renderer.Subject3Renderer;
import net.mcreator.boh.client.renderer.SuicideMouseRenderer;
import net.mcreator.boh.client.renderer.SwampMonsterRenderer;
import net.mcreator.boh.client.renderer.TailsDollRenderer;
import net.mcreator.boh.client.renderer.TailsRenderer;
import net.mcreator.boh.client.renderer.TakenHandsRenderer;
import net.mcreator.boh.client.renderer.TakenPillarRenderer;
import net.mcreator.boh.client.renderer.TamedRatRenderer;
import net.mcreator.boh.client.renderer.TaperecorderbaldiRenderer;
import net.mcreator.boh.client.renderer.TarBallRenderer;
import net.mcreator.boh.client.renderer.TheThingDogRenderer;
import net.mcreator.boh.client.renderer.TheThingVillagerRenderer;
import net.mcreator.boh.client.renderer.TinkyTankRenderer;
import net.mcreator.boh.client.renderer.TinkyWinkyRenderer;
import net.mcreator.boh.client.renderer.TormentPyramidRenderer;
import net.mcreator.boh.client.renderer.TrimmingRenderer;
import net.mcreator.boh.client.renderer.UnicornRenderer;
import net.mcreator.boh.client.renderer.Unown10Renderer;
import net.mcreator.boh.client.renderer.Unown11Renderer;
import net.mcreator.boh.client.renderer.Unown12Renderer;
import net.mcreator.boh.client.renderer.Unown13Renderer;
import net.mcreator.boh.client.renderer.Unown14Renderer;
import net.mcreator.boh.client.renderer.Unown15Renderer;
import net.mcreator.boh.client.renderer.Unown1Renderer;
import net.mcreator.boh.client.renderer.Unown2Renderer;
import net.mcreator.boh.client.renderer.Unown3Renderer;
import net.mcreator.boh.client.renderer.Unown4Renderer;
import net.mcreator.boh.client.renderer.Unown5Renderer;
import net.mcreator.boh.client.renderer.Unown6Renderer;
import net.mcreator.boh.client.renderer.Unown7Renderer;
import net.mcreator.boh.client.renderer.Unown8Renderer;
import net.mcreator.boh.client.renderer.Unown9Renderer;
import net.mcreator.boh.client.renderer.VampireBatRenderer;
import net.mcreator.boh.client.renderer.VampireRenderer;
import net.mcreator.boh.client.renderer.VitaMimicRenderer;
import net.mcreator.boh.client.renderer.WFPistolProjectileRenderer;
import net.mcreator.boh.client.renderer.WarHorseRenderer;
import net.mcreator.boh.client.renderer.WendigoRenderer;
import net.mcreator.boh.client.renderer.WerewolfDummyRenderer;
import net.mcreator.boh.client.renderer.WerewolfRenderer;
import net.mcreator.boh.client.renderer.WhitefaceFriendlyRenderer;
import net.mcreator.boh.client.renderer.WhitefaceRenderer;
import net.mcreator.boh.client.renderer.WillowispRenderer;
import net.mcreator.boh.client.renderer.XenomorphRenderer;
import net.mcreator.boh.compat.M;
import net.mcreator.boh.compat.forge.client.event.RegisterRenderers;
import net.mcreator.boh.compat.mc.client.renderer.entity.ThrownItemRenderer;

public class BohModEntityRenderers {
    @SubscribeEvent
    public void registerEntityRenderers(RegisterRenderers event) {
        M.registerEntityRenderer(event, BohModEntities.BEN_DROWNED.get(), BenDrownedRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.JEFF_THE_KILLER.get(), JeffTheKillerRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SIREN_HEAD.get(), SirenHeadRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.PYRAMID_HEAD.get(), PyramidHeadRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SAW_RUNNER.get(), SawRunnerRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.XENOMORPH.get(), XenomorphRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.FACEHUGGER.get(), FacehuggerRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.CHESTBURSTER.get(), ChestbursterRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.LIFEFORM.get(), LifeformRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SLENDER_MAN.get(), SlenderManRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.DEMOGORGON.get(), DemogorgonRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.GOLD_LOST.get(), GoldLostRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.GOLD_HOSTILE.get(), GoldHostileRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.UNOWN_1.get(), Unown1Renderer::new);
        M.registerEntityRenderer(event, BohModEntities.UNOWN_2.get(), Unown2Renderer::new);
        M.registerEntityRenderer(event, BohModEntities.UNOWN_3.get(), Unown3Renderer::new);
        M.registerEntityRenderer(event, BohModEntities.UNOWN_4.get(), Unown4Renderer::new);
        M.registerEntityRenderer(event, BohModEntities.UNOWN_5.get(), Unown5Renderer::new);
        M.registerEntityRenderer(event, BohModEntities.UNOWN_6.get(), Unown6Renderer::new);
        M.registerEntityRenderer(event, BohModEntities.UNOWN_7.get(), Unown7Renderer::new);
        M.registerEntityRenderer(event, BohModEntities.UNOWN_8.get(), Unown8Renderer::new);
        M.registerEntityRenderer(event, BohModEntities.UNOWN_9.get(), Unown9Renderer::new);
        M.registerEntityRenderer(event, BohModEntities.UNOWN_10.get(), Unown10Renderer::new);
        M.registerEntityRenderer(event, BohModEntities.UNOWN_11.get(), Unown11Renderer::new);
        M.registerEntityRenderer(event, BohModEntities.UNOWN_12.get(), Unown12Renderer::new);
        M.registerEntityRenderer(event, BohModEntities.UNOWN_13.get(), Unown13Renderer::new);
        M.registerEntityRenderer(event, BohModEntities.UNOWN_14.get(), Unown14Renderer::new);
        M.registerEntityRenderer(event, BohModEntities.UNOWN_15.get(), Unown15Renderer::new);
        M.registerEntityRenderer(event, BohModEntities.RAKE.get(), RakeRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.NECO_ARC.get(), NecoArcRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.WHITEFACE.get(), WhitefaceRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.MICHAEL_DAVIES.get(), MichaelDaviesRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SMILE_DOG.get(), SmileDogRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.WHITEFACE_FRIENDLY.get(), WhitefaceFriendlyRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.DECOY_DOG.get(), DecoyDogRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SPRINGTRAP.get(), SpringtrapRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.AO_ONI.get(), AoOniRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.REXY.get(), RexyRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SONIC_EXE.get(), SonicExeRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.EXE_MONITOR.get(), ExeMonitorRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.HEROBRINE.get(), HerobrineRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SIX.get(), SixRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.MOTHMAN.get(), MothmanRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.RAATMA.get(), RaatmaRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.RAT.get(), RatRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SEED_EATER.get(), SeedEaterRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.GASTER.get(), GasterRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.JAMES_SUNDERLAND.get(), JamesSunderlandRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.GRAY_ALIEN.get(), GrayAlienRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SAUCER.get(), SaucerRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SOTIRIS.get(), SotirisRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.RATAZANA.get(), RatazanaRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SOUICHI.get(), SouichiRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SIMONHENRIKSSON.get(), SimonhenrikssonRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.BOOK_SIMON.get(), BookSimonRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.MICHAEL_MYERS.get(), MichaelMyersRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.EYELESS_JACK.get(), EyelessJackRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.WENDIGO.get(), WendigoRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.NEMESIS.get(), NemesisRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.JASON_VOORHEES.get(), JasonVoorheesRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.JASON_MASK.get(), JasonMaskRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.BIG_DADDY.get(), BigDaddyRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.LIGHT_HEAD.get(), LightHeadRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.LITTLE_SISTER.get(), LittleSisterRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.DEER.get(), DeerRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.DEER_MIMIC.get(), DeerMimicRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.KRAMPUS.get(), KrampusRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.GRANNY.get(), GrannyRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.STILTWALKER.get(), StiltwalkerRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.RED.get(), REDRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.CRUCIFIX_PROJECTILE.get(), ThrownItemRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.MOTHMANBAST_PROJECTILE.get(), ThrownItemRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.RAY_GUN_PROJECTILE_PROJECTILE.get(), ThrownItemRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SADAKO.get(), SadakoRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.ENTITY_WELL.get(), EntityWellRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SPECIMEN_9_BOSS.get(), Specimen9BossRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.TAKEN_PILLAR.get(), TakenPillarRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.TAKEN_HANDS.get(), TakenHandsRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.BLOOD_SPILL.get(), BloodSpillRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.TORMENT_PYRAMID.get(), TormentPyramidRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.WF_PISTOL_PROJECTILE.get(), WFPistolProjectileRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.ROLLING_GIANT.get(), RollingGiantRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.FRESNO_NIGHTCRAWLER.get(), FresnoNightcrawlerRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.MARTIAN_DRONE.get(), MartianDroneRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.CHUCKY.get(), ChuckyRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.CHUCKY_GRAB.get(), ChuckyGrabRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.GHOSTFACE.get(), GhostfaceRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.GHOSTFACE_DECOY.get(), GhostfaceDecoyRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.FREDDY_KRUEGER.get(), FreddyKruegerRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.BOILED_ONE.get(), BoiledOneRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.RABBID.get(), RabbidRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.VAMPIRE.get(), VampireRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.VAMPIRE_BAT.get(), VampireBatRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.WEREWOLF.get(), WerewolfRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.GHOST.get(), GhostRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.DEMON.get(), DemonRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SWAMP_MONSTER.get(), SwampMonsterRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.FUWATTI.get(), FuwattiRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.CELEBI.get(), CelebiRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.TAMED_RAT.get(), TamedRatRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.PHANTOM_FREDDY.get(), PhantomFreddyRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.PHANTOM_FOXY.get(), PhantomFoxyRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.PHANTOM_BB.get(), PhantomBBRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.PHANTOM_PUPPET.get(), PhantomPuppetRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.PHANTOM_MANGLE.get(), PhantomMangleRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.PHANTOM_CHICA.get(), PhantomChicaRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.TAILS.get(), TailsRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.GOJI.get(), GojiRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.INK_DEMON.get(), InkDemonRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.PREDATOR.get(), PredatorRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.PREDATOR_SIGHT.get(), PredatorSightRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.ANGLER.get(), AnglerRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SONIC_BOOM.get(), SonicBoomRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.TINKY_WINKY.get(), TinkyWinkyRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.NEWBORN.get(), NewbornRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.CARTOON_CAT.get(), CartoonCatRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.BALDI.get(), BaldiRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.HOLY_WATER.get(), ThrownItemRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.WEREWOLF_DUMMY.get(), WerewolfDummyRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.FIGURE.get(), FigureRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.TAPERECORDERBALDI.get(), TaperecorderbaldiRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.WILLOWISP.get(), WillowispRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.WAR_HORSE.get(), WarHorseRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.FAMINE_HORSE.get(), FamineHorseRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.DEATH_HORSE.get(), DeathHorseRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.PESTILENCE_HORSE.get(), PestilenceHorseRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.UNICORN.get(), UnicornRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.JACKALOPE.get(), JackalopeRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.FLATWOODS_MONSTER.get(), FlatwoodsMonsterRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.REND_PROJECTILE.get(), RendProjectileRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.VITA_MIMIC.get(), VitaMimicRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.TRIMMING.get(), TrimmingRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SUBJECT_3.get(), Subject3Renderer::new);
        M.registerEntityRenderer(event, BohModEntities.PATRICK_BATEMAN.get(), PatrickBatemanRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.LEATHERFACE.get(), LeatherfaceRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.MX.get(), MXRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SCISSORMAN.get(), ScissormanRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.HYPNO.get(), HypnoRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.TINKY_TANK.get(), TinkyTankRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.RUSSIAN_SLEEP_EXPERIMENT.get(), RussianSleepExperimentRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.GRAFTON_MONSTER.get(), GraftonMonsterRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.PUMPKIN_PLAYER.get(), PumpkinPlayerRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.KRASUE.get(), KrasueRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.KIRIE_HIMURO.get(), KirieHimuroRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.LAUGHING_JACK.get(), LaughingJackRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.JANE_THE_KILLER.get(), JaneTheKillerRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.TAR_BALL.get(), TarBallRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.HYPNO_SHOT_PROJECTILE.get(), ThrownItemRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.TAILS_DOLL.get(), TailsDollRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SUICIDE_MOUSE.get(), SuicideMouseRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SQUIDWARD.get(), SquidwardRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SQUIDWARD_DOOMED.get(), SquidwardDoomedRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.SHOTGUN_PROJECTILE.get(), ShotgunProjectileRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.THE_THING_VILLAGER.get(), TheThingVillagerRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.THE_THING_DOG.get(), TheThingDogRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.BLOODWAVE.get(), BloodwaveRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.BRUCE.get(), BruceRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.MOTHLING.get(), MothlingRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.NOTHING_THERE.get(), NothingThereRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.FLOWERS.get(), FlowersRenderer::new);
        M.registerEntityRenderer(event, BohModEntities.NPC_000.get(), NPC000Renderer::new);
    }
}
