package net.mcreator.boh.compat.mc.world.item;

import net.mcreator.boh.compat.registry.LegacyIds;

/** 1.20 Items constants resolved through LegacyIds (Et Futurum targets when installed). Generated by tools/genconsts.sh. */
public final class Items {

    public static final net.minecraft.item.Item WOODEN_AXE = LegacyIds.itemOf("wooden_axe");
    public static final net.minecraft.item.Item BUCKET = LegacyIds.itemOf("bucket");
    public static final net.minecraft.item.Item SHEARS = LegacyIds.itemOf("shears");
    public static final net.minecraft.item.Item STRING = LegacyIds.itemOf("string");
    public static final net.minecraft.item.Item BOOK = LegacyIds.itemOf("book");
    public static final net.minecraft.item.Item APPLE = LegacyIds.itemOf("apple");
    public static final net.minecraft.item.Item WRITABLE_BOOK = LegacyIds.itemOf("writable_book");
    public static final net.minecraft.item.Item WOODEN_SWORD = LegacyIds.itemOf("wooden_sword");
    public static final net.minecraft.item.Item WHEAT = LegacyIds.itemOf("wheat");
    public static final net.minecraft.item.Item SPLASH_POTION = LegacyIds.itemOf("splash_potion");
    public static final net.minecraft.item.Item POTION = LegacyIds.itemOf("potion");
    public static final net.minecraft.item.Item PAPER = LegacyIds.itemOf("paper");
    public static final net.minecraft.item.Item LINGERING_POTION = LegacyIds.itemOf("lingering_potion");
    public static final net.minecraft.item.Item IRON_SWORD = LegacyIds.itemOf("iron_sword");
    public static final net.minecraft.item.Item GLASS_BOTTLE = LegacyIds.itemOf("glass_bottle");
    public static final net.minecraft.item.Item DIAMOND = LegacyIds.itemOf("diamond");
    public static final net.minecraft.item.Item BONE_MEAL = LegacyIds.itemOf("bone_meal");
    public static final net.minecraft.item.Item BONE = LegacyIds.itemOf("bone");
    public static final net.minecraft.item.Item BLACK_DYE = LegacyIds.itemOf("black_dye");
    public static final net.minecraft.item.Item AIR = LegacyIds.itemOf("air");
    public static final net.minecraft.item.Item STONE_SWORD = LegacyIds.itemOf("stone_sword");
    public static final net.minecraft.item.Item STONE_AXE = LegacyIds.itemOf("stone_axe");
    public static final net.minecraft.item.Item RABBIT_HIDE = LegacyIds.itemOf("rabbit_hide");
    public static final net.minecraft.item.Item RABBIT_FOOT = LegacyIds.itemOf("rabbit_foot");
    public static final net.minecraft.item.Item RABBIT = LegacyIds.itemOf("rabbit");
    public static final net.minecraft.item.Item QUARTZ = LegacyIds.itemOf("quartz");
    public static final net.minecraft.item.Item PORKCHOP = LegacyIds.itemOf("porkchop");
    public static final net.minecraft.item.Item PHANTOM_MEMBRANE = LegacyIds.itemOf("phantom_membrane");
    public static final net.minecraft.item.Item NETHERITE_SWORD = LegacyIds.itemOf("netherite_sword");
    public static final net.minecraft.item.Item NETHERITE_AXE = LegacyIds.itemOf("netherite_axe");
    public static final net.minecraft.item.Item MILK_BUCKET = LegacyIds.itemOf("milk_bucket");
    public static final net.minecraft.item.Item LEATHER = LegacyIds.itemOf("leather");
    public static final net.minecraft.item.Item IRON_AXE = LegacyIds.itemOf("iron_axe");
    public static final net.minecraft.item.Item GOLD_NUGGET = LegacyIds.itemOf("gold_nugget");
    public static final net.minecraft.item.Item GOLDEN_SWORD = LegacyIds.itemOf("golden_sword");
    public static final net.minecraft.item.Item GOLDEN_AXE = LegacyIds.itemOf("golden_axe");
    public static final net.minecraft.item.Item ENDER_PEARL = LegacyIds.itemOf("ender_pearl");
    public static final net.minecraft.item.Item EMERALD = LegacyIds.itemOf("emerald");
    public static final net.minecraft.item.Item EGG = LegacyIds.itemOf("egg");
    public static final net.minecraft.item.Item DIAMOND_SWORD = LegacyIds.itemOf("diamond_sword");
    public static final net.minecraft.item.Item DIAMOND_AXE = LegacyIds.itemOf("diamond_axe");
    public static final net.minecraft.item.Item COOKED_RABBIT = LegacyIds.itemOf("cooked_rabbit");
    public static final net.minecraft.item.Item COAL = LegacyIds.itemOf("coal");
    public static final net.minecraft.item.Item CHARCOAL = LegacyIds.itemOf("charcoal");
    public static final net.minecraft.item.Item BOWL = LegacyIds.itemOf("bowl");
    public static final net.minecraft.item.Item AMETHYST_SHARD = LegacyIds.itemOf("amethyst_shard");
    public static final net.minecraft.item.Item IRON_INGOT = LegacyIds.itemOf("iron_ingot");
    public static final net.minecraft.item.Item GOLD_INGOT = LegacyIds.itemOf("gold_ingot");
    public static final net.minecraft.item.Item STICK = LegacyIds.itemOf("stick");
    public static final net.minecraft.item.Item ARROW = LegacyIds.itemOf("arrow");
    public static final net.minecraft.item.Item BOW = LegacyIds.itemOf("bow");
    public static final net.minecraft.item.Item FEATHER = LegacyIds.itemOf("feather");
    public static final net.minecraft.item.Item GUNPOWDER = LegacyIds.itemOf("gunpowder");
    public static final net.minecraft.item.Item BREAD = LegacyIds.itemOf("bread");
    public static final net.minecraft.item.Item FLINT_AND_STEEL = LegacyIds.itemOf("flint_and_steel");
    public static final net.minecraft.item.Item WATER_BUCKET = LegacyIds.itemOf("water_bucket");
    public static final net.minecraft.item.Item TOTEM_OF_UNDYING = LegacyIds.itemOf("totem_of_undying");

    private Items() {}
}
