package net.mcreator.boh.init;

import net.mcreator.boh.compat.mc.core.registries.Registries;
import net.mcreator.boh.compat.mc.network.chat.Component;
import net.minecraft.util.ResourceLocation;
import net.mcreator.boh.compat.mc.world.item.CreativeModeTab;
import net.mcreator.boh.compat.mc.world.item.CreativeModeTabs;
import net.minecraft.block.Block;
import net.mcreator.boh.compat.forge.event.BuildCreativeModeTabContentsEvent;
import cpw.mods.fml.common.eventhandler.SubscribeEvent;
import net.mcreator.boh.compat.forge.registries.DeferredRegister;
import net.mcreator.boh.compat.forge.registries.RegistryObject;
import net.mcreator.boh.compat.M;

public class BohModTabs {

    public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, "boh");

    public static final RegistryObject<CreativeModeTab> ENTITIES = REGISTRY.register("entities", () -> CreativeModeTab.builder().title(Component.translatable("item_group.boh.entities")).icon(() -> M.new_ItemStack(BohModItems.ICON_2.get())).displayItems((parameters, tabData) -> {
        tabData.accept(BohModItems.BEN_DROWNED_SPAWN_EGG.get());
        tabData.accept(BohModItems.JEFF_THE_KILLER_SPAWN_EGG.get());
        tabData.accept(BohModItems.SIREN_HEAD_SPAWN_EGG.get());
        tabData.accept(BohModItems.PYRAMID_HEAD_SPAWN_EGG.get());
        tabData.accept(BohModItems.SAW_RUNNER_SPAWN_EGG.get());
        tabData.accept(BohModItems.XENOMORPH_SPAWN_EGG.get());
        tabData.accept(BohModItems.FACEHUGGER_SPAWN_EGG.get());
        tabData.accept(BohModItems.CHESTBURSTER_SPAWN_EGG.get());
        tabData.accept(BohModItems.LIFEFORM_SPAWN_EGG.get());
        tabData.accept(BohModItems.SLENDER_MAN_SPAWN_EGG.get());
        tabData.accept(BohModItems.DEMOGORGON_SPAWN_EGG.get());
        tabData.accept(BohModItems.GOLD_LOST_SPAWN_EGG.get());
        tabData.accept(BohModItems.RAKE_SPAWN_EGG.get());
        tabData.accept(BohModItems.WHITEFACE_SPAWN_EGG.get());
        tabData.accept(BohModItems.MICHAEL_DAVIES_SPAWN_EGG.get());
        tabData.accept(BohModItems.SMILE_DOG_SPAWN_EGG.get());
        tabData.accept(BohModItems.SPRINGTRAP_SPAWN_EGG.get());
        tabData.accept(BohModItems.AO_ONI_SPAWN_EGG.get());
        tabData.accept(BohModItems.SONIC_EXE_SPAWN_EGG.get());
        tabData.accept(BohModItems.SIX_SPAWN_EGG.get());
        tabData.accept(BohModItems.RAATMA_SPAWN_EGG.get());
        tabData.accept(BohModItems.RAT_SPAWN_EGG.get());
        tabData.accept(BohModItems.GASTER_SPAWN_EGG.get());
        tabData.accept(BohModItems.JAMES_SUNDERLAND_SPAWN_EGG.get());
        tabData.accept(BohModItems.RATAZANA_SPAWN_EGG.get());
        tabData.accept(BohModItems.SOUICHI_SPAWN_EGG.get());
        tabData.accept(BohModItems.SIMONHENRIKSSON_SPAWN_EGG.get());
        tabData.accept(BohModItems.BOOK_SIMON_SPAWN_EGG.get());
        tabData.accept(BohModItems.MICHAEL_MYERS_SPAWN_EGG.get());
        tabData.accept(BohModItems.EYELESS_JACK_SPAWN_EGG.get());
        tabData.accept(BohModItems.WENDIGO_SPAWN_EGG.get());
        tabData.accept(BohModItems.NEMESIS_SPAWN_EGG.get());
        tabData.accept(BohModItems.JASON_VOORHEES_SPAWN_EGG.get());
        tabData.accept(BohModItems.BIG_DADDY_SPAWN_EGG.get());
        tabData.accept(BohModItems.LITTLE_SISTER_SPAWN_EGG.get());
        tabData.accept(BohModItems.DEER_SPAWN_EGG.get());
        tabData.accept(BohModItems.KRAMPUS_SPAWN_EGG.get());
        tabData.accept(BohModItems.SADAKO_SPAWN_EGG.get());
        tabData.accept(BohModItems.SPECIMEN_9_BOSS_SPAWN_EGG.get());
        tabData.accept(BohModItems.ROLLING_GIANT_SPAWN_EGG.get());
        tabData.accept(BohModItems.CHUCKY_SPAWN_EGG.get());
        tabData.accept(BohModItems.GHOSTFACE_SPAWN_EGG.get());
        tabData.accept(BohModItems.REXY_SPAWN_EGG.get());
        tabData.accept(BohModItems.SEED_EATER_SPAWN_EGG.get());
        tabData.accept(BohModItems.STILTWALKER_SPAWN_EGG.get());
        tabData.accept(BohModItems.FREDDY_KRUEGER_SPAWN_EGG.get());
        tabData.accept(BohModItems.BOILED_ONE_SPAWN_EGG.get());
        tabData.accept(BohModItems.CELEBI_SPAWN_EGG.get());
        tabData.accept(BohModItems.GOJI_SPAWN_EGG.get());
        tabData.accept(BohModItems.INK_DEMON_SPAWN_EGG.get());
        tabData.accept(BohModItems.PREDATOR_SPAWN_EGG.get());
        tabData.accept(BohModItems.ANGLER_SPAWN_EGG.get());
        tabData.accept(BohModItems.TINKY_WINKY_SPAWN_EGG.get());
        tabData.accept(BohModItems.NEWBORN_SPAWN_EGG.get());
        tabData.accept(BohModItems.CARTOON_CAT_SPAWN_EGG.get());
        tabData.accept(BohModItems.BALDI_SPAWN_EGG.get());
        tabData.accept(BohModItems.FIGURE_SPAWN_EGG.get());
        tabData.accept(BohModItems.VITA_MIMIC_SPAWN_EGG.get());
        tabData.accept(BohModItems.TRIMMING_SPAWN_EGG.get());
        tabData.accept(BohModItems.SUBJECT_3_SPAWN_EGG.get());
        tabData.accept(BohModItems.PATRICK_BATEMAN_SPAWN_EGG.get());
        tabData.accept(BohModItems.LEATHERFACE_SPAWN_EGG.get());
        tabData.accept(BohModItems.MX_SPAWN_EGG.get());
        tabData.accept(BohModItems.SCISSORMAN_SPAWN_EGG.get());
        tabData.accept(BohModItems.HYPNO_SPAWN_EGG.get());
        tabData.accept(BohModItems.RUSSIAN_SLEEP_EXPERIMENT_SPAWN_EGG.get());
        tabData.accept(BohModItems.PUMPKIN_PLAYER_SPAWN_EGG.get());
        tabData.accept(BohModItems.KRASUE_SPAWN_EGG.get());
        tabData.accept(BohModItems.KIRIE_HIMURO_SPAWN_EGG.get());
        tabData.accept(BohModItems.LAUGHING_JACK_SPAWN_EGG.get());
        tabData.accept(BohModItems.JANE_THE_KILLER_SPAWN_EGG.get());
        tabData.accept(BohModItems.TAILS_DOLL_SPAWN_EGG.get());
        tabData.accept(BohModItems.SUICIDE_MOUSE_SPAWN_EGG.get());
        tabData.accept(BohModItems.SQUIDWARD_SPAWN_EGG.get());
        tabData.accept(BohModItems.BRUCE_SPAWN_EGG.get());
        tabData.accept(BohModItems.NOTHING_THERE_SPAWN_EGG.get());
        tabData.accept(BohModItems.FLOWERS_SPAWN_EGG.get());
        tabData.accept(BohModItems.NPC_000_SPAWN_EGG.get());
    }).withSearchBar().build());

    public static final RegistryObject<CreativeModeTab> BLOCKS = REGISTRY.register("blocks", () -> CreativeModeTab.builder().title(Component.translatable("item_group.boh.blocks")).icon(() -> M.new_ItemStack(BohModItems.ICON_1.get())).displayItems((parameters, tabData) -> {
        tabData.accept(M.asItem(((Block) BohModBlocks.XENOMORPH_BLOOD.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.OVAMORPH.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.DRAWING_SLENDER.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.KINDNESS_FLOWER.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.LIFEFORM_GROWTH.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.VOODOO_DOLL.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SPINEL_ORE_ORE.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.GOJIBREATH.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.ANALOGTVSADAKOC.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.ANALOG_TELEVISION.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BACKROOMS_FLOOR.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BACKROOMS_WALLS.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BACKROOMS_CEILING_TILE.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BACKROOMS_LAMP.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.GAMETABLE.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.TWIG_TRAP.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BACKROOMS_WALLS_TOP.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BACKROOMS_WALLS_BOTTOM.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BACKROOMS_SOCKET.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.PIPE_BLOCK.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.PIPE_BURST.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.RIFT_STABILIZER.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.COMPUTER.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.TUBBY_CUSTARD.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SPINEL_BLOCK.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BLOODSTONE_BLOCK.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BLACK_WALNUT_WOOD.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BLACK_WALNUT_LOG.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BLACK_WALNUT_PLANKS.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BLACK_WALNUT_LEAVES.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BLACK_WALNUT_STAIRS.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BLACK_WALNUT_SLAB.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BLACK_WALNUT_FENCE.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BLACK_WALNUT_FENCE_GATE.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BLACK_WALNUT_PRESSURE_PLATE.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BLACK_WALNUT_BUTTON.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.DOGWOOD_WOOD.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.DOGWOOD_LOG.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.DOGWOOD_PLANKS.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.DOGWOOD_LEAVES.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.DOGWOOD_STAIRS.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.DOGWOOD_SLAB.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.DOGWOOD_FENCE.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.DOGWOOD_FENCE_GATE.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.DOGWOOD_PRESSURE_PLATE.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.DOGWOOD_BUTTON.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SASSAFRAS_WOOD.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SASSAFRAS_LOG.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SASSAFRAS_PLANKS.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SASSAFRAS_LEAVES.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SASSAFRAS_STAIRS.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SASSAFRAS_SLAB.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SASSAFRAS_FENCE.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SASSAFRAS_FENCE_GATE.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SASSAFRAS_PRESSURE_PLATE.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SASSAFRAS_BUTTON.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.JAR_O_WISP.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BLACK_WALNUT_STRIPPED_WOOD.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BLACK_WALNUT_STRIPPED_LOG.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BLACK_WALNUT_DOOR.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BLACK_WALNUT_TRAPDOOR.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.DOGWOOD_STRIPPED_WOOD.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.DOGWOOD_STRIPPED_LOG.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.DOGWOOD_DOOR.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.DOGWOOD_TRAPDOOR.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SASSAFRAS_STRIPPED_WOOD.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SASSAFRAS_STRIPPED_LOG.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SASSAFRAS_DOOR.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SASSAFRAS_TRAPDOOR.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.BLACK_WALLNUT_SAPPLING.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.DOGWOOD_SAPLING.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SASSAFRAS_SAPLING.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.VITA_CRAWL.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SINISTREE_WOOD.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SINISTREE_LOG.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SINISTREE_PLANKS.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SINISTREE_LEAVES.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SINISTREE_STAIRS.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SINISTREE_SLAB.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SINISTREE_FENCE.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SINISTREE_FENCE_GATE.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SINISTREE_PRESSURE_PLATE.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SINISTREE_BUTTON.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SINISTREE_STRIPPED_WOOD.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SINISTREE_STRIPPED_LOG.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SINISTREE_DOOR.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SINISTREE_TRAP_DOOR.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.SINISTREE_SAPLING.get())));
        tabData.accept(M.asItem(((Block) BohModBlocks.STUD_PART.get())));
    }).withSearchBar().withTabsBefore(new ResourceLocation[] { M.getId(ENTITIES) }).build());

    public static final RegistryObject<CreativeModeTab> ITEMS = REGISTRY.register("items", () -> CreativeModeTab.builder().title(Component.translatable("item_group.boh.items")).icon(() -> M.new_ItemStack(BohModItems.ICON_3.get())).displayItems((parameters, tabData) -> {
        tabData.accept(BohModItems.WHITEFACEHEART.get());
        tabData.accept(BohModItems.POLAROID.get());
        tabData.accept(BohModItems.KILLER_KNIFE.get());
        tabData.accept(BohModItems.THE_GREAT_KNIFE.get());
        tabData.accept(BohModItems.SPINEL.get());
        tabData.accept(BohModItems.RAY_GUN.get());
        tabData.accept(BohModItems.SCHIZOSLEDGE.get());
        tabData.accept(BohModItems.SIMONS_BOOK.get());
        tabData.accept(BohModItems.LIVER.get());
        tabData.accept(BohModItems.THE_SLASHER.get());
        tabData.accept(BohModItems.MASSACRE_AXE.get());
        tabData.accept(BohModItems.CRUCIFIXITEM.get());
        tabData.accept(BohModItems.DEER_MASK_HELMET.get());
        tabData.accept(BohModItems.SIRENPHONE.get());
        tabData.accept(BohModItems.VHS_TAPE.get());
        tabData.accept(BohModItems.GOJI_HEAD_HELMET.get());
        tabData.accept(BohModItems.LIFEFORM_EFFIGY.get());
        tabData.accept(BohModItems.WF_PISTOL.get());
        tabData.accept(BohModItems.VENISON.get());
        tabData.accept(BohModItems.COOKED_VENISON.get());
        tabData.accept(BohModItems.SPECIMEN_9_HEAD.get());
        tabData.accept(BohModItems.EXE_BOOTS_BOOTS.get());
        tabData.accept(BohModItems.DESIRE_EDGE.get());
        tabData.accept(BohModItems.GUN_WITH_ONE_BULLET.get());
        tabData.accept(BohModItems.BOWL_CREEPYPASTA.get());
        tabData.accept(BohModItems.BIG_DADDY_DRILL.get());
        tabData.accept(BohModItems.STOP_SIGN.get());
        tabData.accept(BohModItems.TACTICAL_KNIFE.get());
        tabData.accept(BohModItems.PARTY_POPPER.get());
        tabData.accept(BohModItems.CHAINSAW.get());
        tabData.accept(BohModItems.FREDDY_CLAW.get());
        tabData.accept(BohModItems.EXOTIC_SOUL.get());
        tabData.accept(BohModItems.DEMONIC_SOUL.get());
        tabData.accept(BohModItems.KILLERS_SOUL.get());
        tabData.accept(BohModItems.MONSTROUS_SOUL.get());
        tabData.accept(BohModItems.VAMPIRE_BLOOD.get());
        tabData.accept(BohModItems.WEREWOLF_TEETH.get());
        tabData.accept(BohModItems.ECTOPLASM.get());
        tabData.accept(BohModItems.GILL.get());
        tabData.accept(BohModItems.FRIED_GILL.get());
        tabData.accept(BohModItems.DEMONIC_HORN.get());
        tabData.accept(BohModItems.PAINTED_SWORD.get());
        tabData.accept(BohModItems.MACHETE.get());
        tabData.accept(BohModItems.JASONS_MASK_HELMET.get());
        tabData.accept(BohModItems.HAUNTED_PAPER.get());
        tabData.accept(BohModItems.BLOOD_STONE.get());
        tabData.accept(BohModItems.GIANT_SCISSOR.get());
        tabData.accept(M.asItem(((Block) BohModBlocks.DREAM_CATCHER.get())));
        tabData.accept(BohModItems.STEPHANO.get());
        tabData.accept(BohModItems.SOUL_STEALER.get());
        tabData.accept(BohModItems.DIAPER_ARMOR_LEGGINGS.get());
        tabData.accept(BohModItems.HILT_OF_A_BLACKSMITH.get());
        tabData.accept(BohModItems.HOLY_WATER_ITEM.get());
        tabData.accept(BohModItems.APPLALYPSE.get());
        tabData.accept(BohModItems.ZACKS_SCYTHE.get());
        tabData.accept(BohModItems.WALNUT.get());
        tabData.accept(BohModItems.SINGED_DREAM_CATCHER.get());
        tabData.accept(BohModItems.BROKEN_CAMERA.get());
        tabData.accept(BohModItems.HATREDS_END.get());
        tabData.accept(BohModItems.BOOM_STICK.get());
        tabData.accept(BohModItems.CAMERA_OBSCURA.get());
        tabData.accept(BohModItems.MUSIC_DISC_OTHERSIDE_ENIGMA.get());
        tabData.accept(BohModItems.MUSIC_DISC_ENDLESS_HUNGER.get());
        tabData.accept(BohModItems.MUSIC_DISC_HEY_ITS_ME.get());
        tabData.accept(BohModItems.MUSIC_DISC_LAVENDER.get());
        tabData.accept(BohModItems.MUSIC_DISC_MAJIN.get());
        tabData.accept(BohModItems.MUSIC_DISC_PROMISE.get());
        tabData.accept(BohModItems.MUSIC_DISC_WHITENOIZ.get());
        tabData.accept(BohModItems.MUSIC_DISC_TURN_THE_LIGHTS_OFF.get());
        tabData.accept(BohModItems.MUSIC_DISC_TOUCHTONE.get());
        tabData.accept(BohModItems.MUSIC_DISC_DAY_THEME.get());
        tabData.accept(BohModItems.MUSIC_DISC_DESTROYED_KINGDOM.get());
        tabData.accept(BohModItems.HEMOTORRENT.get());
        tabData.accept(BohModItems.BALDI_RULER.get());
        tabData.accept(BohModItems.MUSIC_DISC_SMASHING_WINDSHIELDS.get());
        tabData.accept(BohModItems.BIG_TOP_BURGER.get());
        tabData.accept(BohModItems.MUSIC_DISCS_BOYS.get());
        tabData.accept(BohModItems.MUSIC_DISC_NEUTRAL_01.get());
        tabData.accept(BohModItems.MIMICRY.get());
        tabData.accept(BohModItems.MUSIC_DISC_FLOWERS.get());
        tabData.accept(BohModItems.WHISPERING_THORNS_HELMET.get());
        tabData.accept(BohModItems.MUSIC_DISC_HEAVEN_SAYS.get());
    }).withSearchBar().withTabsBefore(new ResourceLocation[] { M.getId(BLOCKS) }).build());

    public static final RegistryObject<CreativeModeTab> CRYPTIDS = REGISTRY.register("cryptids", () -> CreativeModeTab.builder().title(Component.translatable("item_group.boh.cryptids")).icon(() -> M.new_ItemStack(BohModItems.ICON_4.get())).displayItems((parameters, tabData) -> {
        tabData.accept(BohModItems.MOTHMAN_SPAWN_EGG.get());
        tabData.accept(BohModItems.FRESNO_NIGHTCRAWLER_SPAWN_EGG.get());
        tabData.accept(BohModItems.WILLOWISP_SPAWN_EGG.get());
        tabData.accept(BohModItems.WAR_HORSE_SPAWN_EGG.get());
        tabData.accept(BohModItems.FAMINE_HORSE_SPAWN_EGG.get());
        tabData.accept(BohModItems.DEATH_HORSE_SPAWN_EGG.get());
        tabData.accept(BohModItems.PESTILENCE_HORSE_SPAWN_EGG.get());
        tabData.accept(BohModItems.UNICORN_SPAWN_EGG.get());
        tabData.accept(BohModItems.JACKALOPE_SPAWN_EGG.get());
        tabData.accept(BohModItems.FLATWOODS_MONSTER_SPAWN_EGG.get());
        tabData.accept(BohModItems.GRAFTON_MONSTER_SPAWN_EGG.get());
        tabData.accept(BohModItems.MOTHLING_SPAWN_EGG.get());
    }).withSearchBar().withTabsBefore(new ResourceLocation[] { M.getId(ITEMS) }).build());

    public static final RegistryObject<CreativeModeTab> MONSTERS = REGISTRY.register("monsters", () -> CreativeModeTab.builder().title(Component.translatable("item_group.boh.monsters")).icon(() -> M.new_ItemStack(BohModItems.POLAROID.get())).displayItems((parameters, tabData) -> {
        tabData.accept(BohModItems.GRAY_ALIEN_SPAWN_EGG.get());
        tabData.accept(BohModItems.SAUCER_SPAWN_EGG.get());
        tabData.accept(BohModItems.MARTIAN_DRONE_SPAWN_EGG.get());
        tabData.accept(BohModItems.VAMPIRE_SPAWN_EGG.get());
        tabData.accept(BohModItems.WEREWOLF_SPAWN_EGG.get());
        tabData.accept(BohModItems.GHOST_SPAWN_EGG.get());
        tabData.accept(BohModItems.DEMON_SPAWN_EGG.get());
        tabData.accept(BohModItems.SWAMP_MONSTER_SPAWN_EGG.get());
        tabData.accept(BohModItems.WEREWOLF_DUMMY_SPAWN_EGG.get());
    }).withSearchBar().withTabsBefore(new ResourceLocation[] { M.getId(CRYPTIDS) }).build());

    public static final RegistryObject<CreativeModeTab> DOCUMENTS = REGISTRY.register("documents", () -> CreativeModeTab.builder().title(Component.translatable("item_group.boh.documents")).icon(() -> M.new_ItemStack(BohModItems.HAUNTED_PAPER.get())).displayItems((parameters, tabData) -> {
        tabData.accept(BohModItems.DOCUMENT_XENOMORPH.get());
        tabData.accept(BohModItems.DOCUMENT_SMILE_DOG.get());
        tabData.accept(BohModItems.DOCUMENT_SPRINGTRAP.get());
        tabData.accept(BohModItems.DOCUMENT_REXY.get());
        tabData.accept(BohModItems.DOCUMENT_MOTHMAN.get());
        tabData.accept(BohModItems.DOCUMENT_RATMAA.get());
        tabData.accept(BohModItems.DOCUMENT_SUICHI.get());
        tabData.accept(BohModItems.DOCUMENT_MYERS.get());
        tabData.accept(BohModItems.DOCUMENT_NEMESIS.get());
        tabData.accept(BohModItems.DOCUMENT_BIGDADDY.get());
        tabData.accept(BohModItems.DOCUMENT_ROLLINGGIANT.get());
        tabData.accept(BohModItems.DOCUMENT_GHOSTFACE.get());
        tabData.accept(BohModItems.DOCUMENT_GOJI.get());
        tabData.accept(BohModItems.DOCUMENT_BENDY.get());
        tabData.accept(BohModItems.DOCUMENT_PREDATOR.get());
        tabData.accept(BohModItems.DOCUMENT_ANGLER.get());
        tabData.accept(BohModItems.DOCUMENT_TINKY.get());
        tabData.accept(BohModItems.DOCUMENT_CHUCKY.get());
        tabData.accept(BohModItems.DOCUMENT_CARTOONCAT.get());
        tabData.accept(BohModItems.DOCUMENT_BALDI.get());
        tabData.accept(BohModItems.DOCUMENT_DEMOGORGON.get());
        tabData.accept(BohModItems.DOCUMENT_FIGURE.get());
        tabData.accept(BohModItems.DOCUMENT_JASON.get());
        tabData.accept(BohModItems.DOCUMENT_BATEMAN.get());
        tabData.accept(BohModItems.DOCUMENT_VITA.get());
        tabData.accept(BohModItems.DOCUMENT_SUBJECT_3.get());
        tabData.accept(BohModItems.DOCUMENT_MX.get());
        tabData.accept(BohModItems.DOCUMENT_HYPNO.get());
        tabData.accept(BohModItems.DOCUMENT_SCISSORMAN.get());
        tabData.accept(BohModItems.PUMPKIN_GUY_DOCUMENT.get());
        tabData.accept(BohModItems.DOCUMENT_KIRIE.get());
        tabData.accept(BohModItems.DOCUMENT_BEN_DROWNED.get());
        tabData.accept(BohModItems.DOCUMENT_AO_ONI.get());
        tabData.accept(BohModItems.DOCUMENT_2011_X.get());
        tabData.accept(BohModItems.DOCUMENT_WHITE_FACE.get());
        tabData.accept(BohModItems.DOCUMENT_KRASUE.get());
        tabData.accept(BohModItems.DOCUMENT_GOLD.get());
        tabData.accept(BohModItems.DOCUMENT_SUICIDE_MOUSE.get());
        tabData.accept(BohModItems.DOCUMENT_SQUIDWARD.get());
        tabData.accept(BohModItems.DOCUMENT_TAILSDOLL.get());
        tabData.accept(BohModItems.DOCUMENT_LEATHERFACE.get());
        tabData.accept(BohModItems.DOCUMENT_JANE.get());
        tabData.accept(BohModItems.DOCUMENT_JEFF.get());
        tabData.accept(BohModItems.DOCUMENT_BRUCE.get());
        tabData.accept(BohModItems.DOCUMENT_NOTHING_THERE.get());
        tabData.accept(BohModItems.DOCUMENT_FLOWERS.get());
    }).withSearchBar().withTabsBefore(new ResourceLocation[] { M.getId(MONSTERS) }).build());

    @SubscribeEvent
    public void buildTabContentsVanilla(BuildCreativeModeTabContentsEvent tabData) {
        if (M.getTabKey(tabData) == CreativeModeTabs.FOOD_AND_DRINKS) {
            tabData.accept(BohModItems.PRETZEL.get());
        }
    }
}
