#!/bin/bash
# Regenerates port/src/main/resources/META-INF/boh_at.cfg from tools/at_fields.txt (mod class mcpName).
cd "$(dirname "$0")/.."
JDK="${JDK:-/c/Program Files/Microsoft/jdk-21.0.12.101-hotspot}"
S=ref/mcp/mcp-srg.srg
{
  echo "# Box of Horrors port access transformer (generated by tools/genat.sh from tools/at_fields.txt)"
  while read -r mod cls name; do
    [ -z "$mod" ] && continue
    srg=$(grep -m1 "^FD: $cls/$name " $S | awk '{print $3}' | sed 's#.*/##')
    if [ -z "$srg" ]; then echo "# MISSING $cls $name"; else echo "$mod ${cls//\//.} $srg # $name"; fi
  done < tools/at_fields.txt
} > port/src/main/resources/META-INF/boh_at.cfg
grep -c "^public" port/src/main/resources/META-INF/boh_at.cfg
