#!/bin/bash
# genconsts.sh <Class> <pkgpath under compat/mc> <type FQN> <LegacyIds method> NAMES...
cd "$(dirname "$0")/.."
JDK="${JDK:-/c/Program Files/Microsoft/jdk-21.0.12.101-hotspot}"
cls=$1; pkg=$2; type=$3; method=$4; shift 4
f="port/src/main/java/net/mcreator/boh/compat/mc/$pkg/$cls.java"
{
  echo "package net.mcreator.boh.compat.mc.${pkg//\//.};"
  echo
  echo "import net.mcreator.boh.compat.registry.LegacyIds;"
  echo
  echo "/** 1.20 $cls constants resolved through LegacyIds (Et Futurum targets when installed). Generated by tools/genconsts.sh. */"
  echo "public final class $cls {"
  echo
  for n in "$@"; do
    lower=$(echo "$n" | tr 'A-Z' 'a-z')
    echo "    public static final $type $n = LegacyIds.$method(\"$lower\");"
  done
  echo
  echo "    private $cls() {}"
  echo "}"
} > "$f"
echo "wrote $f"
