import java.io.File;
import java.lang.reflect.*;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.file.*;
import java.util.*;
import java.util.stream.*;

/**
 * Generates net.mcreator.boh.compat.MGen: static delegates M.name(receiver, args) -> receiver.name(args) for the
 * public instance methods of the compat stand-in classes, because the translator routes unknown-receiver calls
 * through M. Methods already present in the M chain (same erased signature) are skipped.
 *
 * args: classesDir classpathFile outFile
 */
public class GenDelegates {

    static final String[] PKGS = { "net/mcreator/boh/compat/mc/", "net/mcreator/boh/compat/forge/",
        "net/mcreator/boh/compat/mojang/", "net/mcreator/boh/compat/client/", "net/mcreator/boh/geo/" };
    /** packages of compat base classes: only names that M does not have at all are delegated */
    static final String[] BASE_PKGS = { "net/mcreator/boh/compat/block/", "net/mcreator/boh/compat/item/",
        "net/mcreator/boh/compat/entity/", "net/mcreator/boh/compat/effect/" };
    static final Set<String> SKIP = new HashSet<>(Arrays.asList("equals", "hashCode", "toString", "getClass", "notify",
        "notifyAll", "wait", "compareTo", "clone", "finalize", "values", "valueOf", "ordinal", "name"));

    public static void main(String[] a) throws Exception {
        Path classes = Paths.get(a[0]);
        List<URL> urls = new ArrayList<>();
        urls.add(classes.toUri().toURL());
        for (String p : new String(Files.readAllBytes(Paths.get(a[1]))).trim().split(File.pathSeparator)) {
            if (!p.isEmpty()) urls.add(new File(p).toURI().toURL());
        }
        URLClassLoader cl = new URLClassLoader(urls.toArray(new URL[0]), null);
        Set<String> existing = new HashSet<>();
        Set<String> existingNames = new HashSet<>();
        Class<?> m = Class.forName("net.mcreator.boh.compat.M", false, cl);
        for (Method x : m.getMethods()) {
            if (!Modifier.isStatic(x.getModifiers()) || x.getDeclaringClass().getSimpleName().equals("MGen")) continue;
            existing.add(sig(x.getName(), x.getParameterTypes()));
            existingNames.add(x.getName());
        }
        List<String> names;
        try (Stream<Path> s = Files.walk(classes)) {
            names = s.map(p -> classes.relativize(p).toString().replace('\\', '/')).filter(n -> n.endsWith(".class"))
                .filter(n -> Arrays.stream(PKGS).anyMatch(n::startsWith) || Arrays.stream(BASE_PKGS).anyMatch(n::startsWith)).sorted().collect(Collectors.toList());
        }
        StringBuilder out = new StringBuilder();
        out.append("package net.mcreator.boh.compat;\n\n");
        out.append("/** GENERATED by tools/GenDelegates.java - do not edit. Receiver-first delegates for compat classes. */\n");
        out.append("@SuppressWarnings({ \"unchecked\", \"rawtypes\", \"deprecation\" })\n");
        out.append("public class MGen {\n\n    protected MGen() {}\n");
        Set<String> generated = new HashSet<>();
        int n = 0;
        for (String name : names) {
            String cn = name.substring(0, name.length() - 6).replace('/', '.');
            boolean base = Arrays.stream(BASE_PKGS).anyMatch(name::startsWith);
            Class<?> c;
            try {
                c = Class.forName(cn, false, cl);
            } catch (Throwable t) {
                continue;
            }
            if (c.isAnonymousClass() || c.isLocalClass() || c.isSynthetic() || !isPublicChain(c)) continue;
            Method[] ms;
            try {
                ms = c.getDeclaredMethods();
            } catch (Throwable t) {
                System.err.println("skip " + cn + ": " + t);
                continue;
            }
            if (!base) {
                Field[] fs;
                try {
                    fs = c.getDeclaredFields();
                } catch (Throwable t) {
                    fs = new Field[0];
                }
                Arrays.sort(fs, Comparator.comparing(Field::getName));
                for (Field f : fs) {
                    int fm = f.getModifiers();
                    if (!Modifier.isPublic(fm) || Modifier.isStatic(fm) || f.isSynthetic() || !isPublicChain(base(f.getType()))) continue;
                    if (c.getTypeParameters().length > 0) continue;
                    String g = sig(f.getName(), new Class<?>[] { c });
                    if (!existing.contains(g) && generated.add(g)) {
                        out.append("\n    public static ").append(type(f.getGenericType(), new HashMap<>())).append(' ').append(f.getName()).append('(')
                            .append(canon(c)).append(" self) {\n        return self.").append(f.getName()).append(";\n    }\n");
                        n++;
                    }
                    if (Modifier.isFinal(fm)) continue;
                    String s = sig("set_" + f.getName(), new Class<?>[] { c, f.getType() });
                    if (!existing.contains(s) && generated.add(s)) {
                        out.append("\n    public static void set_").append(f.getName()).append('(').append(canon(c)).append(" self, ")
                            .append(type(f.getGenericType(), new HashMap<>())).append(" v) {\n        self.").append(f.getName()).append(" = v;\n    }\n");
                        n++;
                    }
                }
            }
            Arrays.sort(ms, Comparator.comparing(Method::toGenericString));
            for (Method x : ms) {
                int mod = x.getModifiers();
                if (!Modifier.isPublic(mod) || Modifier.isStatic(mod) || x.isSynthetic() || x.isBridge()) continue;
                if (SKIP.contains(x.getName())) continue;
                if (!accessible(x)) continue;
                if (base && existingNames.contains(x.getName())) continue;
                Class<?>[] pt = x.getParameterTypes();
                Class<?>[] full = new Class<?>[pt.length + 1];
                full[0] = c;
                System.arraycopy(pt, 0, full, 1, pt.length);
                String s = sig(x.getName(), full);
                if (existing.contains(s) || !generated.add(s)) continue;
                try {
                    out.append(delegate(c, x));
                    n++;
                } catch (Throwable t) {
                    System.err.println("skip " + cn + "." + x.getName() + ": " + t);
                }
            }
        }
        out.append("}\n");
        Files.write(Paths.get(a[2]), out.toString().getBytes("UTF-8"));
        System.out.println("generated " + n + " delegates");
    }

    static boolean accessible(Method x) {
        if (!isPublicChain(base(x.getReturnType()))) return false;
        for (Class<?> p : x.getParameterTypes()) if (!isPublicChain(base(p))) return false;
        return true;
    }

    static Class<?> base(Class<?> c) {
        while (c.isArray()) c = c.getComponentType();
        return c;
    }

    static boolean isPublicChain(Class<?> c) {
        if (c.isPrimitive()) return true;
        for (Class<?> k = c; k != null; k = k.getDeclaringClass()) if (!Modifier.isPublic(k.getModifiers())) return false;
        return true;
    }

    static String sig(String name, Class<?>[] ps) {
        StringBuilder b = new StringBuilder(name).append('(');
        for (Class<?> p : ps) b.append(p.getName()).append(',');
        return b.append(')').toString();
    }

    static String delegate(Class<?> c, Method x) {
        Map<String, String> ren = new HashMap<>();
        List<String> tvs = new ArrayList<>();
        TypeVariable<?>[] ctv = c.getTypeParameters();
        for (TypeVariable<?> v : ctv) ren.put(v.getName(), "C" + v.getName());
        for (TypeVariable<?> v : x.getTypeParameters()) ren.put(v.getName(), v.getName());
        for (TypeVariable<?> v : ctv) tvs.add(tvDecl(v, ren));
        for (TypeVariable<?> v : x.getTypeParameters()) tvs.add(tvDecl(v, ren));
        StringBuilder b = new StringBuilder("\n    public static ");
        if (!tvs.isEmpty()) b.append('<').append(String.join(", ", tvs)).append("> ");
        b.append(type(x.getGenericReturnType(), ren)).append(' ').append(x.getName()).append('(');
        String recv = canon(c);
        if (ctv.length > 0) recv += "<" + Arrays.stream(ctv).map(v -> "C" + v.getName()).collect(Collectors.joining(", ")) + ">";
        b.append(recv).append(" self");
        Type[] gp = x.getGenericParameterTypes();
        if (gp.length != x.getParameterCount()) gp = x.getParameterTypes();
        List<String> args = new ArrayList<>();
        for (int i = 0; i < gp.length; i++) {
            String t = type(gp[i], ren);
            if (x.isVarArgs() && i == gp.length - 1 && t.endsWith("[]")) t = t.substring(0, t.length() - 2) + "...";
            b.append(", ").append(t).append(" a").append(i);
            args.add("a" + i);
        }
        b.append(')');
        Class<?>[] ex = x.getExceptionTypes();
        if (ex.length > 0) b.append(" throws ").append(Arrays.stream(ex).map(GenDelegates::canon).collect(Collectors.joining(", ")));
        b.append(" {\n        ");
        if (x.getReturnType() != void.class) b.append("return ");
        b.append("self.").append(x.getName()).append('(').append(String.join(", ", args)).append(");\n    }\n");
        return b.toString();
    }

    static String tvDecl(TypeVariable<?> v, Map<String, String> ren) {
        String s = ren.get(v.getName());
        List<String> bs = new ArrayList<>();
        for (Type t : v.getBounds()) if (t != Object.class) bs.add(type(t, ren));
        return bs.isEmpty() ? s : s + " extends " + String.join(" & ", bs);
    }

    static String canon(Class<?> c) {
        if (c.isArray()) return canon(c.getComponentType()) + "[]";
        return c.getName().replace('$', '.');
    }

    static String type(Type t, Map<String, String> ren) {
        if (t instanceof Class) return canon((Class<?>) t);
        if (t instanceof TypeVariable) {
            String r = ren.get(((TypeVariable<?>) t).getName());
            return r != null ? r : "Object";
        }
        if (t instanceof GenericArrayType) return type(((GenericArrayType) t).getGenericComponentType(), ren) + "[]";
        if (t instanceof WildcardType) {
            WildcardType w = (WildcardType) t;
            if (w.getLowerBounds().length > 0) return "? super " + type(w.getLowerBounds()[0], ren);
            Type up = w.getUpperBounds()[0];
            return up == Object.class ? "?" : "? extends " + type(up, ren);
        }
        if (t instanceof ParameterizedType) {
            ParameterizedType p = (ParameterizedType) t;
            Class<?> raw = (Class<?>) p.getRawType();
            String s;
            if (p.getOwnerType() instanceof ParameterizedType) s = type(p.getOwnerType(), ren) + "." + raw.getSimpleName();
            else s = canon(raw);
            return s + "<" + Arrays.stream(p.getActualTypeArguments()).map(a -> type(a, ren)).collect(Collectors.joining(", ")) + ">";
        }
        return t.getTypeName();
    }
}
